all: hw1 hw2 hw3 hw4 hw5 hw6 hw7

hw1: hw1.c
	mpicc -o hw1 hw1.c

hw2: hw2.c
	mpicc -o hw2 hw2.c

hw3: hw3.c
	mpicc -o hw3 hw3.c

hw4: hw4.c
	mpicc -o hw4 hw4.c

hw5: hw5.c
	mpicc -o hw5 hw5.c

hw6: hw6.c
	mpicc -o hw6 hw6.c

hw7: hw7.c
	mpicc -o hw7 hw7.c
